# Generated by Django 5.0.4 on 2024-06-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
