# Generated by Django 5.0.4 on 2024-07-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_user_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
    ]
